name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动点击触发打包

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3-pip python3-venv
          sudo apt install -y openjdk-17-jdk unzip

      - name: Install buildozer
        run: pip install buildozer

      - name: Build APK
        run: |
          buildozer init
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
